version: "3.9"

services:
  app:
    build: .
    container_name: wine-classifier
    ports:
      - "8000:8000"   # FastAPI
      - "8888:8888"   # Jupyter Notebook
      - "5000:5000"   # MLflow UI
    volumes:
      - .:/app
    command: >
      sh -c "
        jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser &
        mlflow ui --host 0.0.0.0 --port 5000 &
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "