version: '3.8'

services:
  fastapi:
    image: brychxpin/ailabschool-p1:latest
    container_name: fastapi_app
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks

  mlflow:
    image: brychxpin/ailabschool-p1:latest
    container_name: mlflow_ui
    ports:
      - "5000:5000"
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks

  jupyter:
    image: brychxpin/ailabschool-p1:latest
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--NotebookApp.token=''"]
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks 